version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
         name: installing dependency
         command: npm install

      - run:
         name: building the application
         command: npm start

workflows:
  build_now:
    jobs:
      - build
