version: 2.1
jobs:
  build:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run:
          name: Installing dependency & Creating build
          command: |
            npm install && npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .      

  deploy:
      machine:
          image: ubuntu-2004:202010-01
      steps:
        - attach_workspace:
           at: .
        - checkout
        - run:
           name: Installing AWSCLI
           command: |
             sudo apt update
             sudo apt upgrade -y
             s udo apt install python3-pip
             sudo pip3 install awsebcli --upgrade
        - run: aws s3 sync /build s3://react-weather-app-01

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
         requires:
           - build
         filters:
           branches:
             only: master

